import React from "react";

let Components = {};

Components['LongWhiteDay'] = require('./bullish/LongWhiteDay').default;
Components['BullishHammer'] = require('./bullish/BullishHammer').default;
Components['BullishInvertedHammer'] = require('./bullish/BullishInvertedHammer').default;
Components['BullishEngulfing'] = require('./bullish/BullishEngulfing').default;
Components['BullishHarami'] = require('./bullish/BullishHarami').default;
Components['BullishHaramiCross'] = require('./bullish/BullishHaramiCross').default;
Components['BullishPiercingLine'] = require('./bullish/BullishPiercingLine').default;
Components['BullishDojiStar'] = require('./bullish/BullishDojiStar').default;
Components['BullishMeetingLine'] = require('./bullish/BullishMeetingLine').default;
Components['ThreeWhiteSoldiers'] = require('./bullish/ThreeWhiteSoldiers').default;
Components['MorningStar'] = require('./bullish/MorningStar').default;
Components['MorningStarDoji'] = require('./bullish/MorningStarDoji').default;
Components['AbandonedBaby'] = require('./bullish/AbandonedBaby').default;
Components['TriStar'] = require('./bullish/TriStar').default;
Components['Breakaway'] = require('./bullish/Breakaway').default;
Components['ThreeInsideUp'] = require('./bullish/ThreeInsideUp').default;
Components['ThreeOutsideUp'] = require('./bullish/ThreeOutsideUp').default;
Components['Kicking'] = require('./bullish/Kicking').default;
Components['UniqueThreeRiverBottom'] = require('./bullish/UniqueThreeRiverBottom').default;
Components['ThreeStarsIntheSouth'] = require('./bullish/ThreeStarsIntheSouth').default;
Components['ConcealingSwallow'] = require('./bullish/ConcealingSwallow').default;
Components['StickSandwich'] = require('./bullish/StickSandwich').default;
Components['HomingPigeon'] = require('./bullish/HomingPigeon').default;
Components['LadderBottom'] = require('./bullish/LadderBottom').default;
Components['MatchingLow'] = require('./bullish/MatchingLow').default;

Components['Bearish_LongBlackBody'] = require('./bearish/LongBlackBody').default;
Components['Bearish_HangingMan'] = require('./bearish/HangingMan').default;
Components['Bearish_ShootingStar'] = require('./bearish/ShootingStar').default;
Components['Bearish_BeltHold'] = require('./bearish/BeltHold').default;
Components['Bearish_EngulfingPattern'] = require('./bearish/BearishEngulfingPattern').default;
Components['Bearish_Harami'] = require('./bearish/Harami').default;
Components['Bearish_HaramiCross'] = require('./bearish/HaramiCross').default;
Components['Bearish_DarkCloudCover'] = require('./bearish/DarkCloudCover').default;
Components['Bearish_DojiStar'] = require('./bearish/DojiStar').default;
Components['Bearish_ThreeBlackCrows'] = require('./bearish/ThreeBlackCrows').default;
Components['Bearish_EveningStar'] = require('./bearish/EveningStar').default;
Components['Bearish_EveningDojiStar'] = require('./bearish/EveningDojiStar').default;
Components['Bearish_AbandonedBaby'] = require('./bearish/AbandonedBaby').default;
Components['Bearish_TriStar'] = require('./bearish/TriStar').default;
Components['Bearish_Breakaway'] = require('./bearish/Breakaway').default;
Components['Bearish_ThreeInsideDown'] = require('./bearish/ThreeInsideDown').default;
Components['Bearish_ThreeOutsideDown'] = require('./bearish/ThreeOutsideDown').default;
Components['Bearish_Kicking'] = require('./bearish/Kicking').default;
Components['Bearish_LatterTop'] = require('./bearish/LatterTop').default;
Components['Bearish_MatchingHigh'] = require('./bearish/MatchingHigh').default;
Components['Bearish_MeetingLines'] = require('./bearish/MeetingLines').default;
Components['Bearish_UpsideGapTwoCrows'] = require('./bearish/UpsideGapTwoCrows').default;
Components['Bearish_IdenticalThreeCrows'] = require('./bearish/IdenticalThreeCrows').default;
Components['Bearish_Deliberation'] = require('./bearish/Deliberation').default;
Components['Bearish_AdvanceBlock'] = require('./bearish/AdvanceBlock').default;
Components['Bearish_TwoCrows'] = require('./bearish/TwoCrows').default; 

export default Components;